[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "v0.145.0"
NODE_VERSION = "v23.10.0"
NPM_VERSION = "10.9.2"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "v0.145.0"
NODE_VERSION = "v23.10.0"
NPM_VERSION = "10.9.2"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "v0.145.0"
NODE_VERSION = "v23.10.0"
NPM_VERSION = "10.9.2"

[context.branch-deploy]
command = "npm build && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "v0.145.0"
NODE_VERSION = "v23.10.0"
NPM_VERSION = "10.9.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
