[build]
command = "npm run build"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.130.0"
NODE_VERSION = "v22.5.1"
NPM_VERSION = "10.8.2"

[context.split1]
command = "npm run build"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.130.0"
NODE_VERSION = "v22.5.1"
NPM_VERSION = "10.8.2"

[context.deploy-preview]
command = "npm build && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.130.0"
NODE_VERSION = "v22.5.1"
NPM_VERSION = "10.8.2"

[context.branch-deploy]
command = "npm build && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.130.0"
NODE_VERSION = "v22.5.1"
NPM_VERSION = "10.8.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
